"""cria tabelas iniciais

Revision ID: 3aad3ed6971e
Revises: 
Create Date: 2025-11-07 19:16:12.818538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aad3ed6971e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('nota_fiscal', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('numero_serie', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('EM_ESTOQUE', 'EM_USO', name='statusitem'), nullable=True),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_serie')
    )
    op.create_index(op.f('ix_ativos_id'), 'ativos', ['id'], unique=False)
    op.create_table('perifericos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_item', sa.String(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perifericos_id'), 'perifericos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=10), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('regiao', sa.String(length=50), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_matricula'), 'usuarios', ['matricula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_matricula'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_perifericos_id'), table_name='perifericos')
    op.drop_table('perifericos')
    op.drop_index(op.f('ix_ativos_id'), table_name='ativos')
    op.drop_table('ativos')
    # ### end Alembic commands ###
